export const CISCO_INTERFACE_BRIEF_PATTERNS = [
  'show ip interface brief',
  'list interface status and ip addresses',
  'which interfaces are up or down',
  'display a concise layer 3 interface summary',
  'how do I see IP addresses on all interfaces',
  'show administrative and protocol state',
  'check interface IP address assignment',
  'give me the IOS XE interface summary command',
  'display interface address status',
  'verify which routed ports are operational',
  'show all interface IPs quickly',
  'find administratively down interfaces',
  'check Status and Protocol columns',
  'what command summarizes IPv4 interfaces',
  'inspect interface line protocol states',
  'list ports with assigned addresses',
  'show IP interface overview',
  'verify interface operational state',
  'command for brief IP interface output',
  'how to inspect interfaces without configuration changes',
  'read-only interface address inventory',
  'quick interface health summary',
  'show L3 ports and their states',
  'display interface protocol status',
  'inspect all routed interfaces'
] as const
